### ISSUE TITLE
Failed to install on the XS v5.9

### ISSUE THREAD

**Issue by prashantvc** [mikeyjones/SpecFlow#1]
The addin failed to install on the XS 5.9 on Mac.

I get "Could not read add-in description" error 
See: https://i.imgur.com/XnZmQNs.png

**Comment by mikeyjones** [comment]
Hi @prashantvc 

It looks like Xamarin have added a new mandatory field to the package for 5.9, I'll investigate it and get a new version up ASAP. 

Can check if it did successfully install for you as I have seen add-ins error like this before, but they still successfully install, and this plugin runs fine on 5.9 stable and alpha for the mac, as I have been using it on those for a couple of weeks now.

Thanks

Mike
