### ISSUE TITLE
Step generator error on MacOS and XamarinStudio 5.9.7

### ISSUE THREAD

**Issue by wwojcik** [mikeyjones/SpecFlow#2]
Addin installed and i have files in directory. 
# error Generation error: Directory '/Users/username/Library/Application Support/XamarinStudio-5.0/LocalInstall/Addins/MonoDevelop.TechTalk.SpecFlow.1.9.0.1/....' not found.

Maybe this a problem "/...."

**Comment by mikeyjones** [comment]
Sorry for not replying sooner, did you solve the issue?
