### ISSUE TITLE
Xamarin add in doesn't work on XS 6 beta

### ISSUE THREAD

**Issue by jimbobbennett** [mikeyjones/SpecFlow#3]
The add in for Xamarin Studio is not working on Xamarin Studio 6.  I've got a fork with a fix but I'm having problems where it's not loading additional step assemblies.  Are you still actively maintaining this?

**Comment by jimbobbennett** [comment]
PR for XS 6 support is at https://github.com/mikeyjones/SpecFlow/pull/4

**Comment by mikeyjones** [comment]
I have a working mpack using your pull request. I also updated it to use SpecFlow version 2. Frustratingly it gives me warnings when I install the mpack. Just trying to figure out how to stop the warnings, as soon as I have done that, I'll put the mpack up.

**Comment by jimbobbennett** [comment]
Cool.  I saw TechTalk's repo with their add in and submitted a similar pull request to that.  Their code only builds with a few tweaks to reference projects but it builds against their only branch which I hope is the latest version.  It still doesn't reference stepAssemblies though.

https://github.com/techtalk/SpecFlow.XamarinStudio/pull/1

Thanks for doing this though, once the pack is up I'll blog about it and ask people to update the other blogs that refer to it (e.g. Rob's one http://arteksoftware.com/bdd-tests-with-xamarin-uitest-and-specflow/)

**Comment by mikeyjones** [comment]
I have a fully working build without errors or warnings. I have put it up in releases and updated the readme to give installation instructions, let me know if you have any issues installing it.

I'm glad that people seem to be finding this useful.

**Comment by jimbobbennett** [comment]
Awesome, thanks.  Yeah - we are using spec flow for all our testing using the Visual Studio add-in, but it's nice to be able to use it on Xamarin Studio as the round trip on Android to push builds out is 10 times faster in XS beta.  Really appreciate your work on this!
