### ISSUE TITLE
Cannot install Xamarin Studio 6 version.

### ISSUE THREAD

**Issue by LiohAu** [mikeyjones/SpecFlow#5]
I just updated my XS 5 to XS 6 and obviously the specflow add-in stopped working. So I downloaded the XS 6 version of the add-in, and tried to install it.

But during install I am getting this error : 

![Image of error](http://i.imgur.com/NLz94kq.png)

So should I update to XS 6.1 using the alpha update channel ?

**Comment by LiohAu** [comment]
Installing XS 6.1 solved my problem.

**Comment by mikeyjones** [comment]
Hi LiohAu,

You can install the version that is in the Xamarin Studio add-ins gallery (instructions on how to install are  here: https://github.com/mikeyjones/SpecFlow/issues/6), that version works on XS 6.0. I have been using XS 6.1 and it seems no less stable than XS 6, so it is up to you.

Thanks for pointing out the the mpack does not work on XS 6.0, as well I hadn't realized. I'll try and get an mpack up over the weekend.

Kind Regards

Mike
